// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlider from './HeroSlider';
import ImageGrid from './ImageGrid';

export {
	HeroSlider,
	ImageGrid,
};

export const components = {
	hero_slider: HeroSlider,
	image_grid: ImageGrid,
};
